### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by agarstang** [Ninjigen/PowerShell#5]
It would be nice to rename the repository to something like "PSKeePass" and move the source into the root.

"PowerShell" is quite misleading :)

Regards,
Adam

**Comment by Ninjigen** [comment]
Hi, this repository is named PowerShell since it is supposed to host any number of future PowerShell modules and/or projects.

**Comment by agarstang** [comment]
If that's you workflow then it's understandable :), especially for private repositories. 

However, Git was designed so that each "logically separate" component should be its own repository. It's much easier to merge repositories down the line than split them apart. This philosophy is very prelavent in Github's UI design; this is why the naming is important because from a list of repositories yours could easily appear to be a fork of the official PowerShell repository.

It also makes management and tracking much easier. For example, as a user of your module I may wish to track/contribute to it but not wish to track your other modules.

The above would also make your module more discoverable and may drive contributions.
